name: Build and Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore src/Automatarr.sln
    - name: Build
      run: dotnet build src/Automatarr.sln --no-restore
    - name: Test
      run: dotnet test src/Automatarr.sln --no-build --verbosity normal

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.0.2
      with:
        # The directory where the generated report should be saved.
        targetdir: .
        # Optional title.
        title: Automatarr Coverage

    - name: DocFx
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docfx/docfx.json

    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        # Directory to search for coverage reports.
        directory: .
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
        # Don't upload files to Codecov
        dry_run: true
        # Path to coverage file to upload
        file: coverage.xml
        # Directory in which to execute codecov.sh
        working-directory: .
