name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/Automatarr.sln      
    - name: Build
      run: dotnet build src/Automatarr.sln --no-restore      
    - name: Test
      run: dotnet test src/Automatarr.sln --no-build --verbosity normal
      
    - name: DocFx
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: doc/docfx.json
        
    - name: Add & Commit
      # You may pin to the exact commit or the version.
      # uses: EndBug/add-and-commit@8c12ff729a98cfbcd3fe38b49f55eceb98a5ec02
      uses: EndBug/add-and-commit@v7.5.0
      with:
        # The message for the commit
        message: '[Automated] Updated documentation'
