name: Push Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: DocFx
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docfx/docfx.json
        
    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.5.0
      with:
        message: '[Automated] Updated documentation'
