name: Push Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.0.2
      with:
        # The directory where the generated report should be saved.
        targetdir: .
        # Optional title.
        title: Automatarr Coverage

    - name: DocFx
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docfx/docfx.json

    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        # Directory to search for coverage reports.
        directory: .
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
        # Don't upload files to Codecov
        dry_run: true
        # Path to coverage file to upload
        file: coverage.xml
        # Directory in which to execute codecov.sh
        working-directory: .
        
    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.5.0
      with:
        message: '[Automated] Updated documentation'
