name: Push Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install DocFX
      run: choco install docfx -y

    - name: Restore dependencies
      run: dotnet restore src/Automatarr.sln

    - name: Build
      run: dotnet build src/Automatarr.sln --no-restore

    - name: Generate Web API spec
      run: |
        dotnet tool restore
        dotnet swagger tofile --output docfx/webapi/webapi.json src/Automatarr.WebApi/bin/Debug/net6.0/Automatarr.WebApi.dll v1

    - name: Generate new documentation
      run: docfx docfx/docfx.json
      env:
        DOCFX_SOURCE_BRANCH_NAME: main

    - name: Deploy Documentation
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: docs
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
