name: Push Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install DocFX
      run: choco install docfx -y

    - name: Restore dependencies
      run: dotnet restore src/Automatarr.sln

    - name: Build
      run: dotnet build src/Automatarr.sln --no-restore

    - name: Generate Web API
      run: |
        dotnet tool restore
        dotnet swagger tofile --output docfx/webapi/webapi.json src/Automatarr.WebApi/bin/Debug/net6.0/Automatarr.WebApi.dll v1

    - name: Print dir 1
      run: dir

    - name: Remove old documentation
      run: Remove-Item docs -Recurse

    - name: Print dir 2
      run: dir

    - name: Print dir 2
      run: docfx docfx/docfx.json
      env:
        DOCFX_SOURCE_BRANCH_NAME: $GITHUB_REF_NAME

    - name: Print dir 3
      run: dir

    - name: Git Commit and Push w/ Force Push
      # You may pin to the exact commit or the version.
      # uses: dciborow/commit@a453a2bd73865875107dd85a471a21369d0a12d8
      uses: dciborow/commit@0.0.1
      with:
        # Specify commit message
        commit-message: '[Automated] Updated documentation'
        # Force push
        force-push: true
